# ---
# - hosts: web_servers
#   tasks:
#     - name: Install Apache
#       apt:
#         name: apache2
#         state: present
#     - name: Debug Apache
#       debug:
#         msg: "Apache is installed"

---
- hosts: web_servers
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
    - name: Copy Apache Config
      copy:
        src: apache.conf
        dest: /etc/apache2/apache2.conf
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
