apiVersion: apps/v1
kind: Deployment
metadata:
  name: didi-deployment
  labels:
    app: didi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: didi-app
  template:
    metadata:
      labels:
        app: didi-app
    spec:
      containers:
      - name: didi-app
        image: dianda87/adoptopenjdk-image:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 8080 # this is the port you open on your Dockerfile.

---
apiVersion: v1
kind: Service
metadata:
  name: didi-service
spec:
  selector:
    app: didi-app
  ports:
    - protocol: "TCP"
      port: 8080       # The port that the service is running on in the cluster.
      targetPort: 8080 # The port exposed by the service 
  type: LoadBalancer
